services:
  - type: web
    name: loan-prediction-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.2
      - key: HOST
        value: 0.0.0.0
      - key: PORT
        value: 10000  # Default port, Render will override this
      - key: MODEL_PATH
        value: loan_approval_model.pkl
      - key: SCALER_PATH
        value: scaler.pkl
